version: '2'

services:
  ###
  # Spark sensor demo pipeline
  ###
  namenode:
    image: bde2020/hadoop-namenode:1.0.0
    hostname: namenode
    volumes:
      - ./data/hadoop/namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
      INIT_DAEMON_STEP: setup_hdfs
    env_file:
      - ./config/hadoop/hadoop.env
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.0.0
    hostname: resourcemanager
    env_file:
      - ./config/hadoop/hadoop.env
  historyserver:
    image: bde2020/hadoop-historyserver:1.0.0
    hostname: historyserver
    volumes:
      - ./data/hadoop/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./config/hadoop/hadoop.env
  nodemanager:
    image: bde2020/hadoop-nodemanager:1.0.0
    hostname: nodemanager
    env_file:
      - ./config/hadoop/hadoop.env
  datanode:
    image: bde2020/hadoop-datanode:1.0.0
    hostname: datanode
    env_file:
      - ./config/hadoop/hadoop.env
  master:
    image: bde2020/spark-master:1.5.1-hadoop2.6
    hostname: spark-master
    environment:
      INIT_DAEMON_STEP: setup_spark
    volumes:
      - ./data/spark-master:/data
  worker:
    image: bde2020/spark-worker:1.5.1-hadoop2.6
    links:
      - "master:spark-master"
  demo:
    image: bde2020/demo-spark-sensor-data:v1.2.0
    environment:
      INIT_DAEMON_STEP: compute_aggregations
      HDFS_URL: hdfs://namenode:8020
    links:
      - "master:spark-master"
  integratorui:
    image: bde2020/integrator-ui:latest
    volumes:
      - /home/docker/demo-spark-sensor-data/config/integrator:/app/config
    environment:
      VIRTUAL_HOST: demo.big-data-europe.eu
  ###
  # mu.semte.ch stack
  ###
  monitor:
    image: bde2020/pipeline-monitor-frontend:0.1.0
    links:
      - identifier:backend
    ports:
      - 80:80
  identifier:
    image: semtech/mu-identifier:1.0.0
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    volumes:
      - ./config:/config
  database:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: http://mu.semte.ch/application
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  pipeline:
    image: bde2020/pipeline-service:0.1.0
  initdaemon:
    image: bde2020/init-daemon-service:0.1.0

networks:
  default:
    driver: overlay

