version: '2.1'

services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    hostname: namenode
    volumes:
      - ./data/hadoop/namenode:/hadoop/dfs/name
    expose:
      - "50070"
    environment:
      CSS_SOURCE: "hadoop"
      CLUSTER_NAME: test
      INIT_DAEMON_STEP: setup_hdfs
      VIRTUAL_HOST: hdfs-namenode.big-data-europe.aksw.org
    env_file:
      - ./config/hadoop/hadoop.env
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    hostname: datanode
    volumes:
      - ./data/hadoop/datanode:/hadoop/dfs/data
    expose:
      - "50075"
    environment:
      CSS_SOURCE: "hadoop"
      VIRTUAL_HOST: hdfs-datanode.big-data-europe.aksw.org
      VIRTUAL_PORT: "50075"
    env_file:
      - ./config/hadoop/hadoop.env
    depends_on:
      namenode:
        condition: service_healthy
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
    hostname: resourcemanager
    expose:
      - "8031"
      - "8088"
    environment:
      VIRTUAL_HOST: hdfs-resourcemanager.big-data-europe.aksw.org
      VIRTUAL_PORT: "8088"
      CSS_SOURCE: "hadoop-resource-manager"
    env_file:
      - ./config/hadoop/hadoop.env
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
  historyserver:
    image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
    hostname: historyserver
    volumes:
      - ./data/hadoop/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./config/hadoop/hadoop.env
    environment:
      VIRTUAL_HOST: hdfs-historyserver.big-data-europe.aksw.org
      VIRTUAL_PORT: "8188"
      CSS_SOURCE: "hadoop-history-server"
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
  nodemanager:
    image: bde2020/hadoop-nodemanager:1.1.0-hadoop2.7.1-java8
    hostname: nodemanager
    expose:
      - "8042"
    environment:
      VIRTUAL_HOST: hdfs-nodemanager.big-data-europe.aksw.org
      VIRTUAL_PORT: "8042"
      CSS_SOURCE: "hadoop-node-manager"
    env_file:
      - ./config/hadoop/hadoop.env
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
  filebrowser:
    image: bde2020/hdfs-filebrowser
    hostname: filebrowser
    expose:
      - "8088"
    environment:
      NAMENODE_HOST: namenode
      VIRTUAL_HOST: hue.big-data-europe.aksw.org
      VIRTUAL_PORT: "8088"
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
  spark-master:
    image: bde2020/spark-master:2.0.0-hadoop2.7-hive-java8
    hostname: spark-master
    environment:
      INIT_DAEMON_STEP: setup_spark
      CSS_SOURCE: "spark-master"
      VIRTUAL_HOST: spark-master.big-data-europe.aksw.org
      VIRTUAL_PORT: "8080"
    volumes:
      - ./data/spark-master:/data
    env_file:
      - ./config/hadoop/hadoop.env
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
  spark-worker:
    image: bde2020/spark-worker:2.0.0-hadoop2.7-hive-java8
    environment:
      SPARK_MASTER: spark://spark-master:7077
      CSS_SOURCE: "spark-master"
      VIRTUAL_HOST: spark-worker.big-data-europe.aksw.org
      VIRTUAL_PORT: "8081"
    depends_on:
      spark-master:
        condition: service_healthy
  data-stub:
    image: earthquakesan/bigknob
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
      spark-master:
        condition: service_healthy

  demo:
    image: bde2020/demo-spark-sensor-data:2.0.0
    environment:
      INIT_DAEMON_STEP: compute_aggregations
      HDFS_URL: hdfs://namenode:8020
    depends_on:
      data-stub:
        condition: service_healthy

  integratorui:
    image: bde2020/integrator-ui:latest
    volumes:
      - ./config/integrator:/app/config
    environment:
      VIRTUAL_HOST: demo.big-data-europe.aksw.org

  csswrapper:
    image: bde2020/nginx-proxy-with-css
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  ###
  # mu.semte.ch stack
  ###
  monitor:
    image: bde2020/pipeline-monitor-frontend:0.1.0
    links:
      - identifier:backend
    environment:
      VIRTUAL_HOST: monitor.big-data-europe.aksw.org
  identifier:
    image: semtech/mu-identifier:1.0.0
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    volumes:
      - ./config:/config
  database:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: http://mu.semte.ch/application
      VIRTUAL_HOST: virtuoso.big-data-europe.aksw.org
      VIRTUAL_PORT: "8890"
    volumes:
      - ./data/db:/data
  pipeline:
    image: bde2020/mu-pipeline-service:0.1.0
  initdaemon:
    image: bde2020/mu-init-daemon-service:0.1.0
